from datetime import datetime
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field
from graphiti_core.utils.datetime_utils import utc_now


class SessionRequest(BaseModel):
    """Request model matching Zep Cloud API session creation"""
    session_id: str = Field(..., description='Unique session identifier')
    user_id: str = Field(..., description='User identifier for the session')
    metadata: Dict[str, Any] = Field(default_factory=dict, description='Optional session metadata')


class SessionResponse(BaseModel):
    """Response model matching Zep Cloud API session structure"""
    uuid: str = Field(..., description='Server-generated UUID for the session')
    id: int = Field(..., description='Internal database ID')  
    session_id: str = Field(..., description='User-provided session identifier')
    user_id: str = Field(..., description='User identifier')
    created_at: datetime = Field(..., description='Session creation timestamp')
    updated_at: datetime = Field(..., description='Last update timestamp')
    metadata: Dict[str, Any] = Field(default_factory=dict, description='Session metadata')
    summary: Optional[str] = Field(None, description='Session summary generated by NLP')


class AddMemoryToSessionRequest(BaseModel):
    """Request model for adding memory to a session"""
    messages: list = Field(..., description='List of messages to add to session memory')
    metadata: Dict[str, Any] = Field(default_factory=dict, description='Optional memory metadata')


class SessionMemoryResponse(BaseModel):
    """Response model for session memory retrieval"""
    uuid: str = Field(..., description='Memory UUID')
    session_id: str = Field(..., description='Associated session identifier')
    messages: list = Field(..., description='Messages in session memory')
    relevant_facts: list = Field(default_factory=list, description='Relevant facts extracted from memory')
    summary: Optional[str] = Field(None, description='Session summary')
    metadata: Dict[str, Any] = Field(default_factory=dict, description='Memory metadata')


class SessionListResponse(BaseModel):
    """Response model for listing sessions"""
    sessions: list[SessionResponse] = Field(..., description='List of sessions')
    total_count: int = Field(..., description='Total number of sessions')
    response_count: Optional[int] = Field(None, description='Number of sessions in current response')
    limit: Optional[int] = Field(None, description='Current page limit')
    offset: Optional[int] = Field(None, description='Current page offset')


class SessionMessage(BaseModel):
    """Message model matching Zep Cloud API structure"""
    uuid: str = Field(..., description='Message UUID')
    created_at: datetime = Field(default_factory=utc_now, description='Message creation time')
    role: str = Field(..., description='Message role (user, assistant, system)')
    role_type: str = Field(..., description='Role type classification')
    content: str = Field(..., description='Message content')  
    metadata: Dict[str, Any] = Field(default_factory=dict, description='Message metadata')
    token_count: Optional[int] = Field(None, description='Token count for the message')


class SessionMessagesResponse(BaseModel):
    """Response model for session messages"""
    messages: list[SessionMessage] = Field(..., description='Session messages')
    session_id: str = Field(..., description='Session identifier')
    total_count: int = Field(..., description='Total message count')
    next_cursor: Optional[str] = Field(None, description='Cursor for pagination')